### ISSUE TITLE
Can't run the code on M1 chip macbook pro

### ISSUE THREAD

**Issue by wongsihan** [cmt-dtu-energy/MagTense#24]
ImportError: dlopen(/Users/envy/Documents/GitHub/MagTense/python/magtense/lib/magtensesource.cpython-39-darwin.so, 0x0002): tried: '/Users/envy/Documents/GitHub/MagTense/python/magtense/lib/magtensesource.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

**Comment by spollok** [comment]
@wongsihan Sorry for the long wait. Unfortunately, we do not have an M1 mac in our group in order to reproduce the error.
I guess you were following the instructions from [python/](https://github.com/cmt-dtu-energy/MagTense/tree/master/python) and installed `gfortran` and the `Make utility` as pointed out in Step 2 for MacOS.
I guess the errors originates from the `f2py` command in the Makefile, which might have some problems with the ARM-architecture of the M1 chip.
Maybe you can give [miniforge](https://github.com/conda-forge/miniforge) a try, as suggested [here](https://apple.stackexchange.com/questions/436801/m1-mac-mach-o-file-but-is-an-incompatible-architecture-have-x86-64-need-a) and [here](https://www.hendrik-erz.de/post/setting-up-python-numpy-and-pytorch-natively-on-apple-m1).

**Comment by wongsihan** [comment]
@spollok Thank you very much for your patient reply. I will try this solution. If there is any new progress, I will update it under this issue.
